[2022-10-19 12:00:44,279: ERROR] HTTPSConnectionPool(host='dghj', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10fe313c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
[2022-10-19 12:00:57,509: ERROR] HTTPSConnectionPool(host='dghj', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x109cb7940>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
[2022-10-19 12:07:38,585: ERROR] HTTPSConnectionPool(host='dghj', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10d075390>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
[2022-10-19 12:07:49,800: ERROR] HTTPSConnectionPool(host='dghj', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106895120>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
[2022-10-19 12:08:22,472: ERROR] HTTPSConnectionPool(host='dghj', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1032ad0f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
[2022-10-19 12:27:34,530: ERROR] HTTPSConnectionPool(host='notexist.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:997)')))
[2022-10-19 13:24:35,161: ERROR] HTTPSConnectionPool(host='notexist.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:997)')))
[2022-10-19 13:25:54,164: ERROR] HTTPSConnectionPool(host='notexist.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:997)')))
[2022-10-19 13:29:05,766: ERROR] HTTPSConnectionPool(host='notexist.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:997)')))
[2022-10-19 13:30:24,962: ERROR] HTTPSConnectionPool(host='notexist.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:997)')))
[2022-10-19 13:31:29,490: ERROR] HTTPSConnectionPool(host='notexist.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:997)')))
[2022-10-19 13:40:45,878: ERROR] HTTPSConnectionPool(host='dghj', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10251fa60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
[2022-10-19 13:41:02,136: ERROR] HTTPSConnectionPool(host='dghj', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x109f95480>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
