[2022-10-19 12:00:44,279: ERROR] HTTPSConnectionPool(host='dghj', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10fe313c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
[2022-10-19 12:00:57,509: ERROR] HTTPSConnectionPool(host='dghj', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x109cb7940>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
[2022-10-19 12:07:38,585: ERROR] HTTPSConnectionPool(host='dghj', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10d075390>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
[2022-10-19 12:07:49,800: ERROR] HTTPSConnectionPool(host='dghj', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106895120>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
[2022-10-19 12:08:22,472: ERROR] HTTPSConnectionPool(host='dghj', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1032ad0f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
